services:
  - type: web
    name: spotijudge
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: spotijudge-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: spotijudge-db
    databaseName: spotijudge
    user: spotijudge_user